#!/usr/bin/env python3
"""Embed maintained research chapters into the offline single-page site."""
import argparse
import html
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
START = '<!-- BEGIN GENERATED RESEARCH -->'
END = '<!-- END GENERATED RESEARCH -->'
TOC_START = '<!-- BEGIN RESEARCH NOSCRIPT TOC -->'
TOC_END = '<!-- END RESEARCH NOSCRIPT TOC -->'


def render():
    chapters = json.loads((ROOT / 'content/research-chapters.json').read_text())
    capstone = json.loads((ROOT / 'content/capstone-chapters.json').read_text())
    sources = json.loads((ROOT / 'content/sources.json').read_text())
    source_map = {s['id']: s for s in sources}
    if len(source_map) != len(sources):
        raise ValueError('duplicate source IDs')
    def cite(match):
        s = source_map[match[1]]
        return ('<cite data-source="' + html.escape(s['id'], quote=True) + '"><a href="' +
                html.escape(s['url'], quote=True) + '" target="_blank" rel="noopener">[' +
                html.escape(s['id']) + ']</a></cite>')
    rows = []
    for s in sources:
        rows.append('<tr><td><a href="' + html.escape(s['url'], quote=True) +
                    '" target="_blank" rel="noopener">' + html.escape(s['title']) +
                    '</a><br><code>' + html.escape(s['id']) + '</code></td><td>' +
                    html.escape(s['version']) + '</td><td>' + html.escape(s['scope']) + '</td></tr>')
    table = '<div class="tbl-wrap"><table class="tbl"><thead><tr><th>来源</th><th>版本</th><th>阅读范围</th></tr></thead><tbody>' + ''.join(rows) + '</tbody></table></div>'
    bodies = []
    for c in chapters + capstone:
        body = (ROOT / 'content/chapters' / (c['id'] + '.html')).read_text().strip()
        if f'id="ch-{c["id"]}"' not in body:
            raise ValueError(f'wrong section ID: {c["id"]}')
        body = re.sub(r'<cite data-source="([\w-]+)"></cite>', cite, body)
        bodies.append(body.replace('<!-- SOURCE_TABLE -->', table))
    generated = START + '\n' + '\n\n'.join(bodies) + '\n' + END
    page = (ROOT / 'index.html').read_text()
    if START in page:
        page, n = re.subn(re.escape(START) + '.*?' + re.escape(END), lambda _: generated, page, flags=re.S)
        if n != 1:
            raise ValueError('expected one research block')
    else:
        page = page.replace('  </main>', generated + '\n\n  </main>', 1)
    toc = TOC_START + '\n' + '\n'.join('<li><a href="#ch-' + c['id'] + '">' + html.escape(c['num'] + ' ' + c['title']) + '</a></li>' for c in chapters + capstone) + '\n' + TOC_END
    if TOC_START in page:
        page = re.sub(re.escape(TOC_START) + '.*?' + re.escape(TOC_END), lambda _: toc, page, flags=re.S)
    else:
        page = page.replace('    </ol>\n  </noscript>', toc + '\n    </ol>\n  </noscript>', 1)
    script = '<script src="assets/js/research-data.js?v=20260920e"></script>'
    if not re.search(r'<script src="assets/js/research-data\.js(?:\?[^\"]*)?"', page):
        page = page.replace('<script src="assets/js/app.js', script + '\n<script src="assets/js/research.js?v=20260919r"></script>\n<script src="assets/js/app.js', 1)
    # Invalidate cached UI and metadata together; do not insert duplicate scripts.
    page = re.sub(r'(assets/(?:js/(?:app|data|research-data)\.js|css/main\.css))\?[^\"]+', r'\1?v=20260920e', page)
    js = '/* Generated by scripts/build_research.py; edit content/*.json instead. */\n'
    js += '(function () {\n  var chapters = ' + json.dumps(chapters, ensure_ascii=False, indent=2) + ';\n'
    js += '  DSH.modules.splice(2, 0, {id: "research", name: "论文与实验", desc: "自改机制、统计方法与研究练习", icon: "book"});\n'
    js += '  var after = DSH.chapters.findIndex(function (c) { return c.id === "carriers"; }) + 1;\n'
    js += '  DSH.chapters.splice.apply(DSH.chapters, [after, 0].concat(chapters));\n'
    js += '  var capstone = ' + json.dumps(capstone, ensure_ascii=False, indent=2) + ';\n'
    js += '  DSH.modules.splice(3, 0, {id: "capstone", name: "RepoOps Lab", desc: "仓库运维 Agent 与评测系统", icon: "book"});\n'
    js += '  DSH.chapters.splice.apply(DSH.chapters, [after + chapters.length, 0].concat(capstone));\n'
    js += '  DSH.sources = ' + json.dumps(sources, ensure_ascii=False, indent=2) + ';\n})();\n'
    return {ROOT / 'index.html': page, ROOT / 'assets/js/research-data.js': js}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, text in render().items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(text)
    if stale:
        parser.exit(1, 'Generated content is stale: ' + ', '.join(stale) + '\nRun python scripts/build_research.py\n')
    print('Research content is in sync.' if args.check else 'Research chapters and source registry generated.')


if __name__ == '__main__':
    main()
